name: DAST with OWASP ZAP

on:
  push:
    branches: [ main, testing/dast-pipeline]
  pull_request:
    branches: [ main, testing/dast-pipeline]
    
    
permissions:
  issues: write


jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build container image
        run: |
            docker build -t result-service ./Dockerfile.dev

      - name: Run application container
        run: |
          docker run -d --name result-serv \
            -p 8085:8085 \
            result-service
      # 4. Wait until the app is responding
      - name: Wait for web app to be up
        run: |
          timeout 60 bash -c \
          'until curl -s http://localhost:8085>/dev/null; do sleep 1; done'

      # 5. Run ZAP full scan against localhost
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0

        with:
          target: 'http://127.0.0.1:8085/'
